# Generated by Django 2.0.3 on 2018-04-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='product', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='category', to='shop.Category'),
        ),
    ]
